language: python
python:
- 3.6  
install:
- pip3 install pyftpsync==2.1.0
branches:
  only:
    - master
script:
- pyftpsync upload . --exclude ".git,.travis*" ftp://$FTP_USER:$FTP_PASSWORD@davidgengenbach.de/sites/decentral-card.net/
